  // ===== 官方评分标准（前端内置，单一数据源，与 server.py 硬编码逐字一致）=====
  // 评分标准展示改为「页内可折叠区块」，不再走 /api/standard 网络请求，零缓存、零异步竞态、绝对稳定。
  const STANDARDS = {
    "CET4": { kind:"cet", max:15, source:"《大学英语四、六级考试大纲（2016 修订版）》第 4.1.2 节",
      bands:{ 14:"切题。表达思想清楚，文字通顺、连贯，基本上无语言错误，仅有个别小错",
              11:"切题。表达思想清楚，文字连贯，但有少量语言错误",
              8:"基本切题。表达思想不够清楚，文字勉强连贯，语言错误相当多，有些严重错误",
              5:"基本切题。表达思想不清楚，连贯性差，有较多严重语言错误",
              2:"条理不清，思路紊乱，语言支离破碎或大部分句子有错，多数为严重错误",
              0:"未作答、仅几个孤立词、或完全离题" } },
    "CET6": { kind:"cet", max:15, source:"《大学英语四、六级考试大纲（2016 修订版）》第 4.1.2 节",
      bands:{ 14:"切题。表达思想清楚，文字通顺、连贯，基本上无语言错误，仅有个别小错",
              11:"切题。表达思想清楚，文字连贯，但有少量语言错误",
              8:"基本切题。表达思想不够清楚，文字勉强连贯，语言错误相当多，有些严重错误",
              5:"基本切题。表达思想不清楚，连贯性差，有较多严重语言错误",
              2:"条理不清，思路紊乱，语言支离破碎或大部分句子有错，多数为严重错误",
              0:"未作答、仅几个孤立词、或完全离题" } },
    "考研英一A": { kind:"postgrad", max:20, source:"《全国硕士研究生招生考试英语（一）/（二）考试大纲》",
      bands:{ 5:"很好地完成了试题规定的任务：包含所有内容要点；使用丰富的语法结构和词汇；语言自然流畅，语法错误极少；有效地采用了多种衔接手法，文字连贯，层次清晰；格式与语域恰当贴切。对目标读者完全产生了预期的效果。",
              4:"较好地完成了试题规定的任务：包含所有内容要点，允许漏掉一、两个次重点；使用较丰富的语法结构和词汇；语言基本准确，只有在试图使用较复杂结构或较高级词汇时才有个别错误；采用了适当的衔接手法，层次清晰，组织较严密；格式与语域较恰当。对目标读者产生了预期的效果。",
              3:"基本完成了试题规定的任务：虽漏掉一些内容，但包含多数内容要点；所使用的语法结构和词汇能满足任务的需求；存在一些语法及词汇错误，但不影响整体理解；采用了简单的衔接手法，内容基本连贯，层次基本清晰；格式与语域基本合理。对目标读者基本产生了预期的效果。",
              2:"未能按要求完成试题规定的任务：漏掉或未能有效阐述一些内容要点，写了一些无关内容；语法结构单调、词汇项目有限；有较多语法结构或词汇方面的错误，影响了对写作内容的理解；未采用恰当的衔接手法，内容缺少连贯性；格式和语域不恰当。未能清楚地传达信息给读者。",
              1:"未完成试题规定的任务：明显遗漏主要内容，且有许多不相关的内容；语法项目和词汇的使用单调、重复；语言错误多，有碍读者对内容的理解，语言运用能力差；未使用任何衔接手法，内容不连贯，缺少组织、分段；无格式与语域概念。未能传达信息给读者。",
              0:"所传达的信息或所用语言太少，无法评价；内容与要求无关或无法辨认。" } },
    "考研英一B": { kind:"postgrad", max:20, source:"《全国硕士研究生招生考试英语（一）/（二）考试大纲》",
      bands:{ 5:"很好地完成了试题规定的任务：包含所有内容要点；使用丰富的语法结构和词汇；语言自然流畅，语法错误极少；有效地采用了多种衔接手法，文字连贯，层次清晰；格式与语域恰当贴切。对目标读者完全产生了预期的效果。",
              4:"较好地完成了试题规定的任务：包含所有内容要点，允许漏掉一、两个次重点；使用较丰富的语法结构和词汇；语言基本准确，只有在试图使用较复杂结构或较高级词汇时才有个别错误；采用了适当的衔接手法，层次清晰，组织较严密；格式与语域较恰当。对目标读者产生了预期的效果。",
              3:"基本完成了试题规定的任务：虽漏掉一些内容，但包含多数内容要点；所使用的语法结构和词汇能满足任务的需求；存在一些语法及词汇错误，但不影响整体理解；采用了简单的衔接手法，内容基本连贯，层次基本清晰；格式与语域基本合理。对目标读者基本产生了预期的效果。",
              2:"未能按要求完成试题规定的任务：漏掉或未能有效阐述一些内容要点，写了一些无关内容；语法结构单调、词汇项目有限；有较多语法结构或词汇方面的错误，影响了对写作内容的理解；未采用恰当的衔接手法，内容缺少连贯性；格式和语域不恰当。未能清楚地传达信息给读者。",
              1:"未完成试题规定的任务：明显遗漏主要内容，且有许多不相关的内容；语法项目和词汇的使用单调、重复；语言错误多，有碍读者对内容的理解，语言运用能力差；未使用任何衔接手法，内容不连贯，缺少组织、分段；无格式与语域概念。未能传达信息给读者。",
              0:"所传达的信息或所用语言太少，无法评价；内容与要求无关或无法辨认。" } },
    "考研英二A": { kind:"postgrad", max:15, source:"《全国硕士研究生招生考试英语（一）/（二）考试大纲》",
      bands:{ 5:"很好地完成了试题规定的任务：包含所有内容要点；使用丰富的语法结构和词汇；语言自然流畅，语法错误极少；有效地采用了多种衔接手法，文字连贯，层次清晰；格式与语域恰当贴切。对目标读者完全产生了预期的效果。",
              4:"较好地完成了试题规定的任务：包含所有内容要点，允许漏掉一、两个次重点；使用较丰富的语法结构和词汇；语言基本准确，只有在试图使用较复杂结构或较高级词汇时才有个别错误；采用了适当的衔接手法，层次清晰，组织较严密；格式与语域较恰当。对目标读者产生了预期的效果。",
              3:"基本完成了试题规定的任务：虽漏掉一些内容，但包含多数内容要点；所使用的语法结构和词汇能满足任务的需求；存在一些语法及词汇错误，但不影响整体理解；采用了简单的衔接手法，内容基本连贯，层次基本清晰；格式与语域基本合理。对目标读者基本产生了预期的效果。",
              2:"未能按要求完成试题规定的任务：漏掉或未能有效阐述一些内容要点，写了一些无关内容；语法结构单调、词汇项目有限；有较多语法结构或词汇方面的错误，影响了对写作内容的理解；未采用恰当的衔接手法，内容缺少连贯性；格式和语域不恰当。未能清楚地传达信息给读者。",
              1:"未完成试题规定的任务：明显遗漏主要内容，且有许多不相关的内容；语法项目和词汇的使用单调、重复；语言错误多，有碍读者对内容的理解，语言运用能力差；未使用任何衔接手法，内容不连贯，缺少组织、分段；无格式与语域概念。未能传达信息给读者。",
              0:"所传达的信息或所用语言太少，无法评价；内容与要求无关或无法辨认。" } },
    "考研英二B": { kind:"postgrad", max:15, source:"《全国硕士研究生招生考试英语（一）/（二）考试大纲》",
      bands:{ 5:"很好地完成了试题规定的任务：包含所有内容要点；使用丰富的语法结构和词汇；语言自然流畅，语法错误极少；有效地采用了多种衔接手法，文字连贯，层次清晰；格式与语域恰当贴切。对目标读者完全产生了预期的效果。",
              4:"较好地完成了试题规定的任务：包含所有内容要点，允许漏掉一、两个次重点；使用较丰富的语法结构和词汇；语言基本准确，只有在试图使用较复杂结构或较高级词汇时才有个别错误；采用了适当的衔接手法，层次清晰，组织较严密；格式与语域较恰当。对目标读者产生了预期的效果。",
              3:"基本完成了试题规定的任务：虽漏掉一些内容，但包含多数内容要点；所使用的语法结构和词汇能满足任务的需求；存在一些语法及词汇错误，但不影响整体理解；采用了简单的衔接手法，内容基本连贯，层次基本清晰；格式与语域基本合理。对目标读者基本产生了预期的效果。",
              2:"未能按要求完成试题规定的任务：漏掉或未能有效阐述一些内容要点，写了一些无关内容；语法结构单调、词汇项目有限；有较多语法结构或词汇方面的错误，影响了对写作内容的理解；未采用恰当的衔接手法，内容缺少连贯性；格式和语域不恰当。未能清楚地传达信息给读者。",
              1:"未完成试题规定的任务：明显遗漏主要内容，且有许多不相关的内容；语法项目和词汇的使用单调、重复；语言错误多，有碍读者对内容的理解，语言运用能力差；未使用任何衔接手法，内容不连贯，缺少组织、分段；无格式与语域概念。未能传达信息给读者。",
              0:"所传达的信息或所用语言太少，无法评价；内容与要求无关或无法辨认。" } },
    "高中": { kind:"senior", max:25, source:"高考英语书面表达评分标准（依据教育部考试中心《普通高等学校招生全国统一考试英语科考试大纲》书面表达评分标准；全国卷应用文满分 25 分，分五档）",
      bands:{ 5:"第五档（很好）·21–25 分：完全完成了试题规定的任务；覆盖所有内容要点；应用了较多的语法结构和词汇；语法结构或词汇方面有些许错误，但为尽力使用较复杂结构或较高级词汇所致，具备较强的语言运用能力；有效地使用了语句间的连接成分，使全文结构紧凑；完全达到了预期的写作目的。",
              4:"第四档（好）·16–20 分：完全完成了试题规定的任务；虽漏掉 1、2 个次重点，但覆盖所有主要内容；应用的语法结构和词汇能满足任务的要求；语法结构或词汇方面应用基本准确，些许错误主要是因尝试较复杂语法结构或词汇所致；应用简单的语句间的连接成分，使全文结构紧凑；达到了预期的写作目的。",
              3:"第三档（适当）·11–15 分：基本完成了试题规定的任务；虽漏掉一些内容，但覆盖所有主要内容；应用的语法结构和词汇能满足任务的要求；有一些语法结构或词汇方面的错误，但不影响理解；应用简单的语句间的连接成分，使全文内容连贯；整体而言，基本达到了预期的写作目的。",
              2:"第二档（较差）·6–10 分：未恰当完成试题规定的任务；漏掉或未描述清楚一些主要内容，写了一些无关内容；语法结构单调、词汇项目有限；有一些语法结构或词汇方面的错误，影响了对写作内容的理解；较少使用语句间的连接成分，内容缺少连贯性；信息未能清楚地传达给读者。",
              1:"第一档（差）·1–5 分：未完成试题规定的任务；明显遗漏主要内容，写了一些无关内容，原因可能是未理解试题要求；语法结构单调、词汇项目有限；较多语法结构或词汇方面的错误，影响对写作内容的理解；缺乏语句间的连接成分，内容不连贯；信息未能传达给读者。",
              0:"0 分：未作答；所写内容太少或无法看清以致无法评判；或与题目要求完全不相关。" } },
    "雅思": { kind:"ielts", max:9, source:"IELTS Writing Task 2 Assessment Criteria（British Council / IDP / Cambridge）",
      dims:{
        "Task Response":{ 9:"Fully addresses all parts of the task. Fully developed position with relevant, extended, well-supported ideas.",
          8:"Sufficiently addresses all parts. Well-developed response with relevant, extended, supported ideas.",
          7:"Addresses all parts of the task. Clear position throughout. Main ideas extended and supported, though may overgeneralise or lack focus.",
          6:"Addresses all parts but some more fully than others. Relevant position but conclusions may be unclear or repetitive. Main ideas inadequately developed.",
          5:"Addresses task only partially. Position expressed but development unclear. Main ideas limited or not directly relevant.",
          4:"Addresses the task only partially; format may be inappropriate. Expresses a position but development is not always clear. Main ideas limited and not sufficiently developed.",
          3:"Does not adequately address any part of the task. Does not express a clear position.",
          2:"Barely responds to the task. Does not express a position. May attempt to present one or two ideas but there is no development.",
          1:"Essentially no response; fails to address the task." },
        "Coherence and Cohesion":{ 9:"Cohesion attracts no attention. Skilful paragraphing.",
          8:"Logical sequencing. All cohesion managed well. Paragraphing used sufficiently and appropriately.",
          7:"Logical organisation with clear progression. Range of cohesive devices used appropriately, with some under-/over-use.",
          6:"Coherent arrangement with clear overall progression. Cohesion within/between sentences may be faulty or mechanical.",
          5:"Some organisation but no overall progression. Inadequate or repetitive cohesive devices.",
          4:"Presents information and ideas but these are not arranged coherently. Uses basic cohesive devices but these may be inaccurate or repetitive.",
          3:"Does not organise ideas logically. May use a very limited range of devices, and those used may not indicate a logical relationship between ideas.",
          2:"Has very little control of organisational features.",
          1:"Cannot organise ideas at all." },
        "Lexical Resource":{ 9:"Wide range with very natural and sophisticated control. Rare minor slips.",
          8:"Wide range used fluently and flexibly. Skilful use of uncommon items with occasional inaccuracies. Rare spelling/word-formation errors.",
          7:"Sufficient range for flexibility and precision. Less common items used with awareness of style and collocation. Occasional errors.",
          6:"Adequate range. Attempts less common vocabulary with some inaccuracy. Some spelling errors that don't impede communication.",
          5:"Limited range, minimally adequate. Noticeable errors may cause difficulty for the reader.",
          4:"Uses only basic vocabulary. Limited range; errors may cause difficulty for the reader.",
          3:"Uses only a very limited range of words. Expression with very limited control of word formation and/or spelling.",
          2:"Uses an extremely limited range of vocabulary; essentially no control of word formation and/or spelling.",
          1:"Essentially no vocabulary; cannot use basic words." },
        "Grammatical Range and Accuracy":{ 9:"Wide range with full flexibility and accuracy. Rare slips.",
          8:"Wide range of structures. Majority of sentences error-free.",
          7:"Variety of complex structures. Frequent error-free sentences. Good control.",
          6:"Mix of simple and complex forms. Some errors but communication maintained.",
          5:"Limited range. Frequent errors and faulty punctuation.",
          4:"Uses a limited range of structures. Attempts complex but errors predominate.",
          3:"Attempts sentence forms but errors in grammar and punctuation predominate and distort meaning.",
          2:"Cannot use sentence forms except in memorised phrases.",
          1:"Cannot use sentence forms at all." }
      } }
  };
